CC = gcc
CFLAGS = -Wall -Werror -Wextra -pedantic

0-hreadelf: 0-hreadelf.c
	$(CC) $(CFLAGS) elf.h 0-hreadelf.c -o 0-hreadelf

1-hreadelf:  1-hreadelf.c
	$(CC) $(CFLAGS) elf.h 1-hreadelf.c -o 1-hreadelf
2-hreadelf: 2-hreadelf.c
	$(CC) $(CFLAGS) elf.h 2-hreadelf.c -o 2-hreadelf

100-hreadelf: 100-hreadelf.c
	$(CC) $(CFLAGS) elf.h 100-hreadelf.c -o 100-hreadelf
